name: json_model
description: Gernerating Dart model class from Json files with one command.
version: 1.0.0
homepage: https://github.com/flutterchina/json_model
repository: https://github.com/flutterchina/json_model

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.1.1
  build: ^2.0.3
  glob: ^2.0.1
  logging: ^1.0.1
  io: ^1.0.3
  build_runner_core: ^7.0.0
  build_runner: ^2.0.0
  path: ^1.8.0
dev_dependencies:
  test: ^1.5.1
  lint: ^1.0.0
